//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SqlServerRestApiSample.Models.CountriesWithPeople
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CountriesWithPeopleSampleDatabaseEntities : DbContext
    {
        public CountriesWithPeopleSampleDatabaseEntities()
            : base("name=CountriesWithPeopleSampleDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CountryWithPeople> CountryWithPeoples { get; set; }
        public virtual DbSet<PersonInCountry> PersonInCountries { get; set; }
    }
}
